# common-workflows repo ▸ .github/workflows/prerelease-on-bump.yml
name: Prerelease on Version Bump

on:
  workflow_call:
    secrets:
      # GITHUB_TOKEN:
      #   required: true
      TELEGRAM_TOKEN:
        required: true
    inputs:
      dry-run:
        type: boolean
        default: false

permissions:
  contents: write

env:
  # t.me/alryaz_ha_addons
  TELEGRAM_TO: "-1001326752860"

jobs:
  detect:
    name: Detect Component & Versions
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.detect.outputs.component }}
      compatibility: ${{ steps.get_current.compatibility }}
      current: ${{ steps.get_current.outputs.current }}
      previous: ${{ steps.get_prev.outputs.previous }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect integration directory
        id: detect
        run: |
          DIR_COUNT=$(find custom_components/* -maxdepth 0 -type d | wc -l)
          if [ "$DIR_COUNT" -gt "1" ]; then
            echo "❌ More than one component detected in the repository"
            exit 1
          elif [ "$DIR_COUNT" -lt "1" ]; then
            echo "❌ Components not found in the repository"
            exit 1
          fi
          echo "component=$(basename custom_components/*)" | tee -a "${GITHUB_OUTPUT}"

      - name: Install jq
        run: command -v jq >/dev/null 2>&1 || sudo apt-get install -y jq || sudo apt-get update && sudo apt-get install -y jq

      - name: Get current version and compatibility
        id: get_current
        env:
          MANIFEST: custom_components/${{ steps.detect.outputs.component }}/manifest.json
          IS_DRY_RUN: ${{ inputs.dry-run }}
        run: |
          if [ "${IS_DRY_RUN}" = "true" ]; then
            current=v9999.99.99
          else
            # Notice that we append "v" in front of the version here
            current=v$(jq -r '.version' "${MANIFEST}")
          fi
          echo "current=${current}" | tee -a "${GITHUB_OUTPUT}"

          compatibility=$(jq -r '.homeassistant' hacs.json)
          echo "compatibility=${compatibility}" | tee -a "${GITHUB_OUTPUT}"

      - name: Fail-fast if tag exists
        if: ${{ inputs.dry-run != true && inputs.dry-run != 'true' }}
        env:
          CHECK_TAG: ${{ steps.get_current.outputs.current }}
        run: |
          echo "Checking if tag ${CHECK_TAG} exists..."
          if git rev-parse "${CHECK_TAG}" >/dev/null 2>&1; then
            echo "❌ Tag '${CHECK_TAG}' already exists."
            exit 1
          else
            echo "✅ Tag '${CHECK_TAG}' does not exist."
          fi

      - name: Get previous version/tag
        id: get_prev
        run: |
          previous=$(git tag --list "v*" --sort=-creatordate | head -n1)
          if [ -z "$previous" ]; then
            echo "::notice::Hooray, this is an initial commit!"
            previous=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "previous=${previous}" | tee -a "${GITHUB_OUTPUT}"

  prerelease:
    name: Build & Publish Release
    needs: detect
    if: needs.detect.outputs.current != needs.detect.outputs.previous
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ needs.detect.outputs.component }}
      CURRENT: ${{ needs.detect.outputs.current }}
      PREVIOUS: ${{ needs.detect.outputs.previous }}
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build CHANGELOG
        id: changelog
        run: |
          python3 - <<'EOF' | tee -a "${GITHUB_OUTPUT}"
          import subprocess
          import os
          import re

          categories = {
              'BREAKING CHANGE': ('warning', 'BREAKING CHANGE'),
              'feat': ('new', 'Нововведения'),
              'fix': ('bug', 'Исправления'),
              'refactor': ('wrench', 'Изменения'),
              'other': ('information_source', 'Примечания'),
          }
          lines = subprocess.check_output(
              ['git', 'log', '--pretty-format:"%s%n%b"', os.environ["PREVIOUS"] + '..${{ github.sha }}'],
              text=True,
          )
          contents = {}
          matcher = re.compile(r'^(' + '|'.join(categories) + '|[a-z]+)(?:\([^)]+\))?: *(.*)')
          for line in filter(bool, map(str.strip, lines.splitlines())):
              if m := matcher.match(line):
                  prefix = m.group(1)
                  line = m.group(2)
                  if prefix not in categories:
                      prefix = "other"
              else:
                  prefix = "other"
              if prefix not in contents:
                  contents[prefix] = ["## :" + icon + ": " + title]
              contents.setdefault(prefix, set()).add(line)
          print('changelog<<EOF')
          for category, (icon, title) in categories.items():
              if category not in contents:
                  continue
              print("\n- ".join(contents[category]) + "\n")
          print('EOF')
          EOF

      - name: Create prerelease
        id: create_release
        if: ${{ inputs.dry-run != true && inputs.dry-run != 'true' }}
        uses: actions/github-script@v7
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        with:
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              tag_name: process.env.CURRENT,
              name:     process.env.CURRENT,
              body:     process.env.CHANGELOG,
              prerelease: true
            });

      - name: Zip component
        run: |
          cd "custom_components/${COMPONENT}"
          zip -r ../release.zip .

      - name: Upload ZIP asset
        if: ${{ inputs.dry-run != true && inputs.dry-run != 'true' }}
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.CURRENT }}
          file: ./custom_components/release.zip
          asset_name: ${{ env.COMPONENT }}.zip
          overwrite: true

  notify:
    name: Notify Telegram
    needs: [detect, prerelease]
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq curl

      - name: Prepare prerelease message
        id: prepare
        env:
          CHANGELOG: ${{ needs.prerelease.outputs.changelog }}
          VERSION: ${{ needs.detect.outputs.current }}
          HAMIN: ${{ needs.detect.outputs.compatibility }}
        run: |
          REPO="${GITHUB_REPOSITORY##*/}"
          HACS="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${VERSION}/hacs.json"

          {
            echo "message<<EOF"
            echo "✅ Новый релиз **${VERSION}** проекта **${REPO}** опубликован!"
            echo
            echo "Ссылка на GitHub: $URL"
            echo "Совместимость: HA ≥${compatibility}"
            echo
            echo "#$REPO" | awk -F'-' '{for (i=1; i<=NF; i++) printf i==1 ? tolower($i) : toupper(substr($i,1,1)) tolower(substr($i,2)); print ""}'
            echo "#homeassistant"
            echo "EOF"
          } | tee -a $GITHUB_OUTPUT

      - name: Send Telegram message
        if: ${{ inputs.dry-run != true && inputs.dry-run != 'true' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.prepare.outputs.message }}
          format: markdown
